[package]
name = "smearor-http-service"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
miette = { workspace = true }
paste = { workspace = true }
regex = "1.11"
reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true }
serde_json = { workspace = true }
smearor-http-model = { path = "../../model/http" }
smearor-swipe-launcher-plugin-api = { path = "../../plugin-api" }
stabby = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[package.metadata.deb]
name = "smearor-service-http"
depends = "$auto, smearor-swipe-launcher (>= 0.1.0)"
assets = [
    ["../../target/release/libsmearor_http_service.so", "/usr/lib/smearor/", "644"],
]
