[package]
name = "smearor-voice-assistant-service"
version = "0.1.0"
description = "Voice assistant service plugin for the Smearor Swipe Launcher"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = { workspace = true }
cpal = { workspace = true }
encoding_rs = { workspace = true }
espeak-ng = { workspace = true }
fastembed = { workspace = true }
glob = "0.3"
glib = { workspace = true }
hf-hub = { workspace = true }
llama-cpp-4 = { workspace = true }
llm_json = "1.0"
miette = { workspace = true }
moka = { workspace = true }
ndarray = { workspace = true }
ort = { workspace = true }
oww-rs = { workspace = true }
gguf = { workspace = true }
paste = { workspace = true }
regex = { workspace = true }
ringbuf = { workspace = true }
rusqlite = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
shellexpand = { workspace = true }
smearor-personalization-model = { path = "../../model/personalization" }
smearor-doa-model = { path = "../../model/doa" }
smearor-swipe-launcher-plugin-api = { path = "../../plugin-api" }
text-processing-rs = { workspace = true }
toml = { workspace = true }
unicode-normalization = { workspace = true }
smearor-model-mcp = { path = "../../model/mcp" }
smearor-voice-assistant-model = { path = "../../model/voice_assistant" }
stabby = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
whisper-rs = { workspace = true }

[features]
default = []
ryzen-5-8500g = ["llm-vulkan", "whisper-vulkan", "whisper-tracing"]
ryzen-9-9950x3d = ["llm-vulkan", "whisper-vulkan", "ort-rocm", "whisper-hipblas", "whisper-tracing"]
ryzen-9-9950x3d-hipblas = ["llm-hipblas", "whisper-vulkan", "ort-rocm", "whisper-hipblas", "whisper-tracing"]
llm-vulkan = ["llama-cpp-4/vulkan"]
llm-hipblas = ["llama-cpp-4/hip"]
ort-cuda = ["ort/cuda"]
ort-rocm = ["ort/rocm"]
whisper-cuda = ["whisper-rs/cuda"]
whisper-hipblas = ["whisper-rs/hipblas"]
whisper-tracing = ["whisper-rs/tracing_backend"]
whisper-vulkan = ["whisper-rs/vulkan"]

[package.metadata.deb]
name = "smearor-service-voice-assistant"
depends = "libstdc++6, libssl3t64, libglib2.0-0t64, libasound2t64, libgomp1, smearor-swipe-launcher (>= 0.1.0), smearor-service-personalization (>= 0.1.0)"
assets = [
    ["target/release/libsmearor_voice_assistant_service.so", "/usr/lib/smearor/", "755"],
    ["target/release/libllama.so.0", "/usr/lib/smearor/", "644"],
    ["target/release/libllama.so", "/usr/lib/smearor/", "644"],
    ["target/release/libggml.so.0", "/usr/lib/smearor/", "644"],
    ["target/release/libggml.so", "/usr/lib/smearor/", "644"],
    ["target/release/libggml-base.so.0", "/usr/lib/smearor/", "644"],
    ["target/release/libggml-base.so", "/usr/lib/smearor/", "644"],
    ["target/release/libggml-cpu.so.0", "/usr/lib/smearor/", "644"],
    ["target/release/libggml-cpu.so", "/usr/lib/smearor/", "644"],
]

[package.metadata.deb.variants.vulkan]
name = "smearor-service-voice-assistant-vulkan"
depends = "libstdc++6, libssl3t64, libglib2.0-0t64, libasound2t64, libgomp1, libvulkan1, smearor-swipe-launcher (>= 0.1.0), smearor-service-personalization (>= 0.1.0)"
assets = [
    ["target/release/libsmearor_voice_assistant_service.so", "/usr/lib/smearor/", "755"],
    ["target/release/libllama.so.0", "/usr/lib/smearor/", "644"],
    ["target/release/libllama.so", "/usr/lib/smearor/", "644"],
    ["target/release/libggml.so.0", "/usr/lib/smearor/", "644"],
    ["target/release/libggml.so", "/usr/lib/smearor/", "644"],
    ["target/release/libggml-base.so.0", "/usr/lib/smearor/", "644"],
    ["target/release/libggml-base.so", "/usr/lib/smearor/", "644"],
    ["target/release/libggml-cpu.so.0", "/usr/lib/smearor/", "644"],
    ["target/release/libggml-cpu.so", "/usr/lib/smearor/", "644"],
    ["target/release/libggml-vulkan.so.0", "/usr/lib/smearor/", "644"],
    ["target/release/libggml-vulkan.so", "/usr/lib/smearor/", "644"],
]

[package.metadata.deb.variants.hipblas]
name = "smearor-service-voice-assistant-hipblas"
depends = "libstdc++6, libssl3t64, libglib2.0-0t64, libasound2t64, libgomp1, libvulkan1, rocblas, rocm-core, smearor-swipe-launcher (>= 0.1.0), smearor-service-personalization (>= 0.1.0)"
assets = [
    ["target/release/libsmearor_voice_assistant_service.so", "/usr/lib/smearor/", "755"],
    ["target/release/libllama.so.0", "/usr/lib/smearor/", "644"],
    ["target/release/libllama.so", "/usr/lib/smearor/", "644"],
    ["target/release/libggml.so.0", "/usr/lib/smearor/", "644"],
    ["target/release/libggml.so", "/usr/lib/smearor/", "644"],
    ["target/release/libggml-base.so.0", "/usr/lib/smearor/", "644"],
    ["target/release/libggml-base.so", "/usr/lib/smearor/", "644"],
    ["target/release/libggml-cpu.so.0", "/usr/lib/smearor/", "644"],
    ["target/release/libggml-cpu.so", "/usr/lib/smearor/", "644"],
    ["target/release/libggml-vulkan.so.0", "/usr/lib/smearor/", "644"],
    ["target/release/libggml-vulkan.so", "/usr/lib/smearor/", "644"],
    ["target/release/libggml-hipblas.so.0", "/usr/lib/smearor/", "644"],
    ["target/release/libggml-hipblas.so", "/usr/lib/smearor/", "644"],
]
