[package]
name = "smearor-voice-assistant-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
cpal = { workspace = true }
encoding_rs = { workspace = true }
glib = { workspace = true }
llama-cpp-4 = { workspace = true }
miette = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smearor-swipe-launcher-plugin-api = { path = "../../plugin-api" }
smearor-model-mcp = { path = "../../model/mcp" }
smearor-voice-assistant-model = { path = "../../model/voice_assistant" }
stabby = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
whisper-rs = { workspace = true }
