[package]
name = "smearor-gnome-service"
version = "0.1.0"
description = "GNOME compositor service plugin for the Smearor Swipe Launcher"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
gio = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
stabby = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
zbus = { workspace = true }
smearor-model-compositor = { path = "../../model/workspace" }
smearor-swipe-launcher-plugin-api = { path = "../../plugin-api" }

[package.metadata.deb]
name = "smearor-service-gnome"
depends = "$auto, smearor-swipe-launcher (>= 0.1.0)"
assets = [
    ["target/release/libsmearor_gnome_service.so", "/usr/lib/smearor/", "644"],
]
