[[themes]]
name = "Smearor"
description = "Die schönsten Hintergründe für den Tisch"
preview_image_path = ""
preview_icon = "nf-weather-stars"
wallpaper_type = "Video"
config.Video.directory = "/home/aschaeffer/Videos/Backgrounds"
config.Video.outputs = ["ALL"]
config.Video.loop_playlist = true
config.Video.shuffle = false
config.Video.muted = true
config.Video.volume = 0
config.Video.speed_percentage = 100
config.Video.extra_arguments = []

[[themes]]
name = "Nature"
description = "Panoramic nature videos"
preview_image_path = ""
preview_icon = "nf-md-pine_tree"
wallpaper_type = "Video"
config.Video.directory = "/home/aschaeffer/Videos/Nature"
config.Video.outputs = ["ALL"]
config.Video.loop_playlist = true
config.Video.shuffle = false
config.Video.muted = true
config.Video.volume = 0
config.Video.speed_percentage = 100
config.Video.extra_arguments = []

[[themes]]
name = "Fauna und Flora"
description = "Zeigt Fauna und Flora"
preview_image_path = ""
preview_icon = "nf-md-flower"
wallpaper_type = "Video"
config.Video.directory = "/home/aschaeffer/Videos/Fauna Landscape"
config.Video.outputs = ["ALL"]
config.Video.loop_playlist = true
config.Video.shuffle = false
config.Video.muted = true
config.Video.volume = 0
config.Video.speed_percentage = 100
config.Video.extra_arguments = []

[[themes]]
name = "Looping"
description = "Hintergründe, die sich endlos wiederholen"
preview_image_path = ""
preview_icon = "nf-md-infinity"
wallpaper_type = "Video"
config.Video.directory = "/home/aschaeffer/Videos/Looping Backgrounds"
config.Video.outputs = ["ALL"]
config.Video.loop_playlist = true
config.Video.shuffle = false
config.Video.muted = true
config.Video.volume = 0
config.Video.speed_percentage = 100
config.Video.extra_arguments = []

[[themes]]
name = "Astro"
description = "Astronomie Videos"
preview_image_path = ""
preview_icon = "nf-fae-planet"
wallpaper_type = "Video"
config.Video.directory = "/home/aschaeffer/Videos/Astro"
config.Video.outputs = ["ALL"]
config.Video.loop_playlist = true
config.Video.shuffle = false
config.Video.muted = true
config.Video.volume = 0
config.Video.speed_percentage = 100
config.Video.extra_arguments = []

[[themes]]
name = "Nature Portrait"
description = "Portrait nature videos"
preview_image_path = ""
preview_icon = "nf-md-phone_rotate_portrait"
wallpaper_type = "Video"
config.Video.directory = "/home/aschaeffer/Videos/Nature Portrait"
config.Video.outputs = ["ALL"]
config.Video.loop_playlist = true
config.Video.shuffle = false
config.Video.muted = true
config.Video.volume = 0
config.Video.speed_percentage = 100
config.Video.extra_arguments = ["video-rotate=90"]

[[themes]]
name = "Tischdecken"
description = "Einige nette Tischdecken für den Tisch, z.B. wenn man frühstücken möchte"
preview_image_path = ""
preview_icon = "nf-md-table-furniture"
wallpaper_type = "Image"
config.Image.directory = "/home/aschaeffer/Bilder/Backgrounds/Tischdecke"
config.Image.outputs = ["ALL"]
config.Image.display_duration_ms = 30000
config.Image.shuffle = true
config.Image.transitions = false
config.Image.transition_effect = "fade"
config.Image.transition_duration_ms = 1000
config.Image.extra_arguments = []

[[themes]]
name = "Travel"
description = "Zeigt Hintergründe für Reisen"
preview_image_path = ""
preview_icon = "nf-fa-suitcase"
wallpaper_type = "Image"
config.Image.directory = "/home/aschaeffer/Bilder/Backgrounds/Travel"
config.Image.outputs = ["ALL"]
config.Image.display_duration_ms = 30000
config.Image.shuffle = true
config.Image.transitions = false
config.Image.transition_effect = "fade"
config.Image.transition_duration_ms = 1000
config.Image.extra_arguments = []

[[themes]]
name = "Tønsåsheia"
description = ""
preview_image_path = ""
preview_icon = "nf-md-ski_cross_country"
wallpaper_type = "Image"
config.Image.directory = "/home/aschaeffer/Bilder/Gallerie/Norwegen/2025/2025-07-04-Tønsåsheia"
config.Image.outputs = ["ALL"]
config.Image.display_duration_ms = 30000
config.Image.shuffle = true
config.Image.transitions = false
config.Image.transition_effect = "fade"
config.Image.transition_duration_ms = 1000
config.Image.extra_arguments = []
