[package]
name = "smearor-network-widget"
version = "0.1.0"
description = "Network status widget plugin for the Smearor Swipe Launcher"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
glib = { workspace = true }
gtk4 = { workspace = true }
miette = { workspace = true }
paste = { workspace = true }
qrcode = "0.14"
serde = { workspace = true }
schemars = { workspace = true }
serde_json = { workspace = true }
smearor-model-mcp = { path = "../../model/mcp" }
smearor-model-widget = { path = "../../model/widget" }
smearor-network-model = { path = "../../model/network" }
smearor-personalization-model = { path = "../../model/personalization" }
smearor-render-utils = { path = "../render-utils" }
smearor-swipe-launcher-plugin-api = { path = "../../plugin-api" }
stabby = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
typed-builder = { workspace = true }

[package.metadata.deb]
name = "smearor-plugin-network"
depends = "$auto, smearor-swipe-launcher (>= 0.1.0), smearor-service-network (>= 0.1.0), smearor-service-personalization (>= 0.1.0)"
assets = [
    ["target/release/libsmearor_network_widget.so", "/usr/lib/smearor/", "644"],
]
