#!/bin/sh
set -e

case "$1" in
    configure)
        if command -v udevadm >/dev/null 2>&1; then
            udevadm control --reload-rules || true
            udevadm trigger --subsystem-match=hidraw --action=change || true
        fi
        ;;
esac

#DEBHELPER#
