[package]
name = "smearor-hyprland-status"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
stabby = { workspace = true, features = ["serde"] }
smearor-hyprland-shared = { path = "../hyprland-shared" }
smearor-swipe-launcher-plugin-api = { path = "../../plugin-api" }
