[package]
name = "smearor-hyprland-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
smearor-hyprland-shared = { path = "../hyprland-shared" }
smearor-hyprland-dispatch = { path = "../hyprland-dispatch" }
smearor-hyprland-status = { path = "../hyprland-status" }
smearor-hyprland-command = { path = "../hyprland-command" }
smearor-swipe-launcher-plugin-api = { path = "../../plugin-api" }
