[package]
name = "smearor-app-launcher-service"
version = "0.1.0"
description = "App launcher service plugin for the Smearor Swipe Launcher"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
stabby = { workspace = true }
dirs = { workspace = true }
freedesktop_entry_parser = { workspace = true }
glib = { workspace = true }
gtk4 = { workspace = true }
miette = { workspace = true }
paste = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
smearor-swipe-launcher-plugin-api = { path = "../../plugin-api" }
smearor-app-launcher-model = { path = "../../model/app-launcher" }
smearor-model-mcp = { path = "../../model/mcp" }
smearor-wrot-process = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
typed-builder = { workspace = true }

[package.metadata.deb]
name = "smearor-service-app-launcher"
depends = "$auto, smearor-swipe-launcher (>= 0.1.0)"
assets = [
    ["target/release/libsmearor_app_launcher_service.so", "/usr/lib/smearor/", "644"],
]
