[package]
name = "smearor-model-compositor"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
stabby = { workspace = true, features = ["serde"] }
smearor-model-mcp = { path = "../mcp" }
smearor-swipe-launcher-plugin-api = { path = "../../plugin-api" }
