#![recursion_limit = "512"]

use smearor_wrot_rotation::SmearorRotation;

mod action;
mod atomic;
mod config;
mod context;
mod css;
mod error;
mod gesture;
mod graphic;
mod json_converter;
mod locale;
pub mod log_forward;
mod mcp;
mod messages;
mod meta;
mod nerd_font;
mod service;
mod type_id;
mod web;
mod widget;

pub use action::ActionBinding;
pub use action::ActionBindings;
pub use action::ActionKind;
pub use action::BindingMode;
pub use action::ClickBinding;
pub use action::CompoundLongpressBinding;
pub use action::DefaultFallback;
pub use action::DispatchableBinding;
pub use action::DoublePressBinding;
pub use action::HoldBinding;
pub use action::InitBinding;
pub use action::LongpressBinding;
pub use action::MiddleClickBinding;
pub use action::ResolvedAction;
pub use action::RightClickBinding;
pub use action::ScrollDownBinding;
pub use action::ScrollUpBinding;
pub use action::SwipeDownBinding;
pub use action::SwipeUpBinding;
pub use action::UnknownActionKindError;
pub use atomic::AtomicAction;
pub use atomic::AtomicGraphicData;
pub use atomic::AtomicGraphicRenderer;
pub use atomic::AtomicRenderMode;
pub use atomic::AtomicWidgetBuildParams;
pub use atomic::AtomicWidgetConfig;
pub use atomic::SpanActionHandler;
pub use atomic::UnknownAtomicActionError;
pub use atomic::build_atomic_widget;
pub use atomic::render_atomic_graphic_default;
pub use atomic::update_labels;
pub use config::PluginConfig;
pub use context::FfiCoreContext;
pub use context::MessageBrokerHandle;
pub use context::PluginExecutor;
pub use context::dummy_broker_send;
pub use context::dummy_executor_spawn;
pub use css::sanitize_css_class_name;
pub use error::PluginConstructionError;
pub use error::PluginConstructionErrorWrapper;
pub use gesture::DEFAULT_SWIPE_THRESHOLD;
pub use gesture::GestureHandler;
pub use gesture::GestureHandlersConfiguration;
pub use graphic::FfiGraphic;
pub use graphic::GraphicRenderer;
pub use json_converter::DestroyPayloadFn;
pub use json_converter::JsonConverterEntry;
pub use json_converter::JsonConverterRegistry;
pub use json_converter::JsonConvertible;
pub use json_converter::JsonDeserializerFn;
pub use json_converter::RegisterJsonConverterFn;
pub use json_converter::dummy_register_json_converter;
pub use json_converter::register_json_converter;
pub use locale::FromLocale;
pub use locale::Locale;
pub use log_forward::LogForwardFn;
pub use log_forward::LogForwardHandle;
pub use log_forward::dummy_log_forward;
pub use log_forward::init_plugin_tracing;
pub use mcp::McpCapabilitiesRegistrator;
pub use messages::AcceptTopic;
pub use messages::FfiEnvelope;
pub use messages::FfiEnvelopePayload;
pub use messages::MessageBroadcaster;
pub use messages::MessageBroadcasterInner;
pub use messages::MessageHandler;
pub use messages::MessageRouter;
pub use messages::MessageTopic;
pub use messages::MessageTopicBroadcaster;
pub use messages::SharedMessage;
pub use messages::box_payload;
pub use messages::default_clone_payload;
pub use messages::default_destroy_payload;
pub use meta::PluginMeta;
pub use meta::PluginMetaGetter;
pub use meta::PluginMetaRaw;
pub use nerd_font::apply_icon_color;
pub use nerd_font::apply_text_color;
pub use nerd_font::resolve_gtk_nerd_icon;
pub use service::SERVICE_VTABLE_VERSION;
pub use service::ServicePlugin;
pub use service::ServicePluginConstructor;
pub use service::ServicePluginContainer;
pub use service::ServicePluginVTable;
pub use type_id::TypedMessage;
pub use type_id::generate_type_id;
pub use web::FfiHtmlString;
pub use web::WebRenderer;
pub use widget::Color;
pub use widget::ColorParseError;
pub use widget::DEFAULT_ICON_COLOR;
pub use widget::DEFAULT_ICON_ONLY;
pub use widget::DEFAULT_ICON_SIZE;
pub use widget::DEFAULT_INFO_TEXT_COLOR;
pub use widget::DEFAULT_MAIN_TEXT_COLOR;
pub use widget::DEFAULT_WIDE_MODE_WIDGET_WIDTH;
pub use widget::DEFAULT_WIDGET_HEIGHT;
pub use widget::DEFAULT_WIDGET_MODE;
pub use widget::DEFAULT_WIDGET_SPACING;
pub use widget::DEFAULT_WIDGET_WIDTH;
pub use widget::FfiWidget;
pub use widget::FfiWidgetBuilder;
pub use widget::PLUGIN_VTABLE_VERSION;
pub use widget::ViewData;
pub use widget::WidgetBuilder;
pub use widget::WidgetDimensions;
pub use widget::WidgetIcon;
pub use widget::WidgetIconRendering;
pub use widget::WidgetLayout;
pub use widget::WidgetMode;
pub use widget::WidgetPlugin;
pub use widget::WidgetPluginConstructor;
pub use widget::WidgetPluginContainer;
pub use widget::WidgetPluginVTable;
pub use widget::WidgetTextColors;
pub use widget::apply_widget_css_class;
pub use widget::apply_widget_css_classes;

pub type Rotation = SmearorRotation;
