#![recursion_limit = "512"]

use smearor_wrot_rotation::SmearorRotation;

mod config;
mod context;
mod error;
mod json_converter;
mod r#macro;
mod messages;
mod meta;
mod nerd_font;
mod plugin;
mod service;
mod type_id;
mod widget;

pub use config::PluginConfig;
pub use context::FfiCoreContext;
pub use context::MessageBrokerHandle;
pub use context::PluginExecutor;
pub use context::dummy_broker_send;
pub use context::dummy_executor_spawn;
pub use error::PluginConstructionError;
pub use error::PluginConstructionErrorWrapper;
pub use json_converter::DestroyPayloadFn;
pub use json_converter::JsonConverterEntry;
pub use json_converter::JsonConverterRegistry;
pub use json_converter::JsonConvertible;
pub use json_converter::JsonDeserializerFn;
pub use json_converter::RegisterJsonConverterFn;
pub use json_converter::dummy_register_json_converter;
pub use json_converter::register_json_converter;
pub use messages::AcceptTopic;
pub use messages::FfiEnvelope;
pub use messages::FfiEnvelopePayload;
pub use messages::MessageBroadcaster;
pub use messages::MessageBroadcasterInner;
pub use messages::MessageHandler;
pub use messages::MessageRouter;
pub use messages::MessageTopic;
pub use messages::MessageTopicBroadcaster;
pub use messages::SharedMessage;
pub use messages::default_destroy_payload;
pub use meta::PluginMeta;
pub use meta::PluginMetaGetter;
pub use meta::PluginMetaRaw;
pub use nerd_font::resolve_gtk_nerd_icon;
pub use plugin::PLUGIN_VTABLE_VERSION;
pub use plugin::Plugin;
pub use plugin::PluginConstructor;
pub use plugin::PluginContainer;
pub use plugin::PluginVTable;
pub use service::SERVICE_VTABLE_VERSION;
pub use service::Service;
pub use service::ServiceConstructor;
pub use service::ServiceContainer;
pub use service::ServiceVTable;
pub use type_id::TypedMessage;
pub use type_id::generate_type_id;
pub use widget::FfiWidget;
pub use widget::FfiWidgetBuilder;
pub use widget::WidgetBuilder;

pub type Rotation = SmearorRotation;
